name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - name: Add remote
        shell: bash
        run: |
          sudo apt update
          sudo apt-get install -y git-lfs
          sudo git lfs migrate import
      - name: Add remote
        env:
          HF: ${{ secrets.HF }}
        run: git remote add space https://sudhakar272:$HF@huggingface.co/spaces/sudhakar272/CatDogDemo
      - name: Push to hub
        env:
          HF: ${{ secrets.HF }}
        run: git push --force https://sudhakar272:$HF@huggingface.co/spaces/sudhakar272/CatDogDemo main

